version: '3'

services:
  docker-mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=employee
      - MYSQL_PASSWORD=root
      - MYSQL_USERNAME=root

  app:
    image: zenapi
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/employee?autoReconnect=true&useSSL=false
    depends_on:
      - docker-mysql